### ISSUE TITLE
Unsatisfied dependency: nim (>= 0.18.1), latest release is 0.18.0

### ISSUE THREAD

**Issue by isaz** [treeform/typography#1]
Hello @treeform, nice package you're working on.
I'm trying to see if I could use it in a little project I have in mind..
```
> nimble install typography
Downloading https://github.com/treeform/typography.git using git
  Verifying dependencies for typography@0.2.0
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Unsatisfied dependency: nim (>= 0.18.1)
```
Is this intentional?

**Comment by treeform** [comment]
Yes Unfortunately. In nim land 0.18.1 means "head" version of the compiler. There has been a major change in the way it handles nil and "" strings. Code here relies on this change.

It could probably back-ported if you really need too stick with 0.18.0 for some reason.

This is how I install the 0.18.1 version: https://github.com/nim-lang/Nim#compiling directly from github.

**Comment by treeform** [comment]
Works with new version 0.19.0.
