### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Benjamin-Lee** [treeform/typography#10]
relay -> rely

**Comment by treeform** [comment]
I can't find it any more. Must have been an older version of the read me?

Thank you for reporting it though!

**Comment by Benjamin-Lee** [comment]
Still there.

> It does not **relay** on any external

> It does **relay** on stb_image

Both should read `rely`

**Comment by treeform** [comment]
Crap you are totally right! Sorry for some reason I was looking at the fidget repo. 

Fixed!
