### ISSUE TITLE
Error when calling up() while in first line of an empty textbox.

### ISSUE THREAD

**Issue by MnlPhlp** [treeform/typography#11]
I got this error while using fidget.
When up() is called while the cursor is in the first line of an empty textbox an error occurs.
In fidget this happens when pressing the up key in an empty box before writing anything.

```
D:\Programming\nim\nhGui\src\nhGui.nim(159) nhGui
C:\Users\manni\.nimble\pkgs\fidget-0.2.1\fidget\backendopengl.nim(284) startFidget
C:\Users\manni\.nimble\pkgs\fidget-0.2.1\fidget\openglbackend\base.nim(57) tick
C:\Users\manni\.nimble\pkgs\fidget-0.2.1\fidget\openglbackend\base.nim(238) onSetKey
C:\Users\manni\.nimble\pkgs\typography-0.2.3\typography\textboxes.nim(327) up
C:\Users\manni\.choosenim\toolchains\nim-1.0.4\lib\system\fatal.nim(39) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexError]
```
The error seems to be that up() tries to acces the first glyph (```layout[0]```) wich doesn't exist.
```nim
 elif textBox.cursorPos.y == textBox.layout[0].selectRect.y:
    # are we on the first line? then jump to start location 0
    textBox.cursor = 0
```
The same thing happens with down().
In that case checking if the ```layout``` seq is empty will probably be enough.

```nim
elif textbox.layout.len != 0 and textBox.cursorPos.y == textBox.layout[^1].selectRect.y:
    # are we on the last line? then jump to start location last
```

I would submit a PR but i don't know how to fix the first problem.

**Comment by treeform** [comment]
I would rather just bail out early. I think that's the best way.

I added tests and fixed the issue: https://github.com/treeform/typography/commit/3a91181fc5b3965c1747322575afa079ea861b8d
