### ISSUE TITLE
`font.drawText` used in asynchronous functions, error.

### ISSUE THREAD

**Issue by lihf8515** [treeform/typography#32]
`font.drawText` used in asynchronous functions, error is prompted at compile time, error message is This expression is not GC-safe.Annotate the proc with {. gcsafe.}to get extended error information.

**Comment by treeform** [comment]
Sorry it can't be gc safe because it uses internal cache. You would probably need to put "async" lock around the method. Then turn off with gc safety check with `{.gcsafe}:` ... block.
