### ISSUE TITLE
Consider linking to the Flippy API docs in functions returning Image

### ISSUE THREAD

**Issue by chr-1x** [treeform/typography#4]
As it is, I had to dig through the dependencies to find which one exported `Image`. It'll save readers of the docs some time if you link [directly to flippy's docs](https://treeform.github.io/flippy/)

**Comment by treeform** [comment]
How can I make the code more clear so it's clear it's returning a Flippy image?

**Comment by chr-1x** [comment]
Just a link in the docs for the functions that return Image would be good enough. It would be great if the "Image" return value in the function signature was a link but I don't know if nimdoc makes that possible or not.

**Comment by treeform** [comment]
I have added the links: https://github.com/treeform/typography/commit/b421a488145466c3b7f3ca4735a1de6974e1a9f0

Thanks!
