### ISSUE TITLE
Unable to import typography threw fidget

### ISSUE THREAD

**Issue by 0x454d505459** [treeform/typography#77]
Hi, when I try to import fidget or compile one of the fidget examples, the compiler yells at me
```fish
/home/gabriel/.nimble/pkgs/typography-0.7.11/typography/rasterizer.nim(214, 23) Error: type mismatch: got <PathCommand>
but expected one of:
macro `.`(v: GVec234; fields: untyped): untyped
  first type mismatch at position: 1
  required type for v: GVec234
  but expression 'c' is of type: PathCommand

expression: numbers(c)

```
Im using an updated artix linux

**Comment by treeform** [comment]
I think you have old version of `fidget` or `typography` installed. Please update both to most recent one.

**Comment by 0x454d505459** [comment]
I got recent one, I installed them from github just yesterday

**Comment by 0x454d505459** [comment]
Got fidget 0.7.8 and typography 0.7.11

**Comment by treeform** [comment]
We probably just need another release, so we made 0.7.12.

See if installing typography 0.7.12 fixes it for you?

**Comment by 0x454d505459** [comment]
Thanks, It works now!
