### ISSUE TITLE
how to get itterable objects like seq

### ISSUE THREAD

**Issue by sk-Prime** [treeform/typography#8]
hi, i am new nim user. As a practice, i am making a simple drawing library <a href="https://github.com/sk-Prime/nimDraw">"github NimDraw"</a> using <a href="https://github.com/jangko/nimPNG">nimPNG</a> 
i want to add text support for it. I have learned that i need to make rasterization of a text before applying it to an image. in the package i have `Canvas` type which is actually seq of pixels. if i can get pixel coordination (e.g. start point (0,0) ) from `typography` i can use for loop to place pixel with selected color on the canvas.

so how can get pixel coordination using typography.
thanks in advance.

**Comment by treeform** [comment]
I recommend looking at how drawText does it:
https://github.com/treeform/typography/blob/master/src/typography/layout.nim#L249

```nim
  ## Draws layout
  for pos in layout:
    var font = pos.font
    if pos.character in font.glyphs:
      var glyph = font.glyphs[pos.character]
      var glyphOffset: Vec2
      let img = font.getGlyphImage(glyph, glyphOffset, subPixelShift=pos.subPixelShift)
      image.blit(
        img,
        rect(
          0, 0,
          float img.width, float img.height
        ),
        rect(
          pos.rect.x + glyphOffset.x, pos.rect.y + glyphOffset.y,
          float img.width, float img.height
        )
      )
```

**Comment by treeform** [comment]
I also added an SDL example:
https://github.com/treeform/typography/blob/master/tests/sdlexample.nim#L108
