### ISSUE TITLE
Compiler error while trying to launch fidget

### ISSUE THREAD

**Issue by artemonster** [treeform/typography#81]
trying to launch fidget with: nim c -r minimal
getting: 
/home/artemonster/.nimble/pkgs/typography-0.7.12/typography/font.nim(96, 28) Error: type mismatch: got <Path>
but expected one of:
macro `.`(v: GVec234; fields: untyped): untyped
  first type mismatch at position: 1
  required type for v: GVec234
  but expression 'glyph.path' is of type: Path
proc commandsToShapes(glyph: Glyph)
  first type mismatch at position: 1
  required type for glyph: Glyph
  but expression 'glyph.path' is of type: Path

expression: commandsToShapes(glyph.path)

Nim version:
artemonster@artemonster:~/nim/fidget/examples/minimal$ nim -v
Nim Compiler Version 1.6.0 [Linux: amd64]
Compiled at 2021-10-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 727c6378d2464090564dbcd9bc8b9ac648467e38
active boot switches: -d:release

**Comment by treeform** [comment]
With the new release https://github.com/treeform/fidget/releases/tag/0.7.9 this should be fixed. Please let me know it it does not work for you.
